CREATE DATABASE TEST1;
USE TEST1;
SELECT VERSION();
SELECT CURDATE();
CREATE TABLE Product (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Quantity INT,
    PRIMARY KEY (ProductID)
);

SELECT * FROM Product;
